name: university_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.7
  connectivity_plus: ^3.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  beamer: ^1.5.3
  cloud_firestore: ^4.2.0
  fluttertoast: ^8.1.2
  flutter_riverpod: ^2.0.2
  http: ^0.13.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  lottie: ^2.0.0
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
